name: Docker Image CI
on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}
            refs/head/main

      - name: Build images
        uses: docker/build-push-action@v6
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          tags: reminder-server:latest
          load: true
          context: .
          file: ./docker/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Docker build
        run: |
          ./docker/docker-build.sh

      - name: Create .env
        run: |
          touch .env

      - name: Docker run
        run: |
          ./docker/docker-run.sh

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache